displayName: Traefik Deep Linking
type: middleware

import: github.com/milosdjurdjevic/traefik-deep-linking-middleware

summary: '[DeepLinking] Traefik Middleware for Deep Linking'

testData:
  mobile-redirect:
    redirects:
      /validate-email: "app://validate-email"
      /change-email: "app://change-email"
      /forgot-password: "app://forgot-password"