displayName: Traefik Deep Linking
type: middleware
iconPath: .assets/icon.png

import: github.com/traefik/plugindemo

summary: '
  This plugin is a Traefik middleware that redirects mobile users to a specific URL.
  It checks the user agent and if it matches a mobile device, it redirects to the specified URL.
  Otherwise, it allows the request to continue to the original destination.'

testData:
  plugin:
    mobile-redirect:
      redirects:
        /validate-email: "app://validate-email"
        /change-email: "app://change-email"
        /forgot-password: "app://forgot-password"
        /change-email: "app://change-email"